### ISSUE TITLE
Test case uses dust scenario 8. Not standard

### ISSUE THREAD

**Issue by aaronreichmenberliner** [aymeric-spiga/mcd-python#32]
The current `test_mcd.def` uses a dust/solar scenario =8 which is not standard in `mpl`

Suggestion which to `1` so the full file should be

```
m     
315   
0.0   
3      
500  
0    
0. 
0. 
1   
1                 
1                 


This file can be use as an input to the example program test_mcd. Just type:

test_mcd.py < test_mcd.def
```

**Comment by aymeric-spiga** [comment]
You are right, let me fix this. This was not a problem in MCD version 4, but now in MCD version 5, some cases are only included in the add-ons version.
