### ISSUE TITLE
Request for Python3 Version

### ISSUE THREAD

**Issue by aaronreichmenberliner** [aymeric-spiga/mcd-python#35]
Hey @aymeric-spiga,

I have been tinkering with integrating this mcd-python module with other programs, but those are written in Python3. Is there a way to update the `mcd.py` and `mcdcomp.py` to python 3 compatible files?

Also, there seems to be a problem with the `from fmcd import dataloc` When running from a python 3 kernel.

Thoughts?

**Comment by aaronreichmenberliner** [comment]
This can be done using the `2to3` package and the `re

* Run `2to3 -v -n -W -f all mcd.py`
* Run `2to3 -v -n -W -f all mcdcomp.py`
* Run `reindent mcd.py`
* Run `reindent mcdcomp.py`

Then upgrade to the appropriate `basemap` in python3.

**Comment by aymeric-spiga** [comment]
I have not worked on converting the script to Python 3 yet. But I like your solution, it is great. Let me reference that in the README
