### ISSUE TITLE
fmcd.log in compile_fmcd.sh

### ISSUE THREAD

**Issue by antoine-bierjon** [aymeric-spiga/mcd-python#45]
In the default version, compile_fmcd.sh calls f2py a first time :
f2py -h fmcd$num.pyf -m fmcd$num tmp.call_mcd.F tmp.julian.F tmp.heights.F > fmcd$num.log 2>&1
which creates the files fmcd$num.pyf and fmcd$num.log

However, the fmcd$num.log file is erased by another fmcd$num.log created by the 2nd call to f2py :
f2py -c fmcd$num.pyf tmp.call_mcd.F tmp.julian.F tmp.heights.F --fcompiler=gnu95 \
  -L$NETCDF/lib -lnetcdf \
  -lm -I$NETCDF/include \
  --f90flags="-fPIC" \
  --f77flags="-fPIC" \
  --verbose \
  \> fmcd$num.log 2>&1

One should create a .log for each f2py calls, or write the 2nd log in the same file, following the 1st log (as it is done for the .pyf file). This only affects debugging, not production.

**Comment by aymeric-spiga** [comment]
This is a great comment, the second > should be replaced by >> I guess. You can commit this, this is good that all logs are available

**Comment by aymeric-spiga** [comment]
You can commit this on master branch, I meant

**Comment by antoine-bierjon** [comment]
Fixed by commit https://github.com/aymeric-spiga/mcd-python/commit/babd3252a4cc6748a156aa65c1e953ef28e4513b on master branch.

**Comment by antoine-bierjon** [comment]
Fixed by commit https://github.com/aymeric-spiga/mcd-python/commit/9b364822050b3fe5156311886b7eb2a1bd471805 on vcd_py2.7 branch.

**Comment by aymeric-spiga** [comment]
great!
